spring:
  application:
    name: splitApp

  datasource:
    url: jdbc:postgresql://localhost:5432/splitapp
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: splitapp-super-secret-key-minimum-256-bits-long-for-hs256
      expiration: 86400000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs